Cinema_Hope_Solution/Cinema_Hope/Controllers/CinemasController.cs
using Microsoft.AspNetCore.Authorization;

namespace Cinema_Hope.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CinemasController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ILocationService _locationService; // Service
        private readonly ICinemaService _cinemaService; // Service
        private readonly IMapper _mapper; // Service


        public CinemasController(ApplicationDbContext context, ILocationService locationService, ICinemaService cinemaService, IMapper mapper)
        {
            _context = context;
            _locationService = locationService;
            _cinemaService = cinemaService;
            _mapper = mapper;
        }

        // GET: Cinemas
        public async Task<IActionResult> Index()
        {
            var cinemas = await _cinemaService.GetAllAsync();
            return View(cinemas);
        }



        public IActionResult Details(int id)
        {
            var cinema = _cinemaService.GetById( (int) id);

            if (cinema is null)
                return NotFound();

            return View(cinema);
        }


        [HttpGet]
        public IActionResult Create()
        {
            Create_CinemaViewModel model = new()
            {
                Locations = _locationService.GetSelectListOf_Locations()
            };

            return View(model);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Create_CinemaViewModel model)
        {
            if (! ModelState.IsValid)
            {
                // after that model is not vaild remember to initialize nessury field of model before return it.

                model.Locations = _locationService.GetSelectListOf_Locations();
                return View(model);
            }

            // let cinema service do create and save to database
            await _cinemaService.Create(model);
           
            return RedirectToAction(nameof(Index));
        }


        [HttpGet]
        public IActionResult Edit(int id)
        {
            Cinema? cinemaInDB = _cinemaService.GetById(id);

            if (cinemaInDB is null)
                return NotFound();

            // pass data to ViewModel From Entity In DB
            Edit_Cinema_ViewModel viewModel = new()
            {
                Name = cinemaInDB.Name,
                Address = cinemaInDB.Address,
                CinemaId = cinemaInDB.CinemaId,
                Email = cinemaInDB.Email,
                LocationId = cinemaInDB.LocationId,
                Phone = cinemaInDB.Phone,
                PostalCode = cinemaInDB.PostalCode,
                Locations = _locationService.GetSelectListOf_Locations()
            };

            return View(viewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit( Edit_Cinema_ViewModel model )
        {
            if (!ModelState.IsValid)
            {
                // after that model is not vaild remember to initialize nessury field of model before return it.

                model.Locations = _locationService.GetSelectListOf_Locations();
                return View(model);
            }

            // Save Entity To Database using Service : var entity = _service.Edit(model)
            Cinema? cinemaToDB = await _cinemaService.Edit(model);

            // check if entity null , means that BadRequest
            if (cinemaToDB is null)
                return BadRequest();

            return RedirectToAction(nameof(Index));
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            bool isDeleted = await _cinemaService.DeleteAsync(id);

            return isDeleted ? Ok() : BadRequest("Bad Requist");
        }

        //======= api
        [HttpGet]
        public async Task<IActionResult> AllCinemas()
        {
            IEnumerable<Cinema> cinemas = await _cinemaService.GetAllAsync();

            IEnumerable<CinemaDto> cinemasDto = _mapper.Map<IEnumerable<CinemaDto>>(cinemas);

            return Ok(cinemasDto);
        }

    }
}

Cinema_Hope_Solution/Cinema_Hope/Controllers/MoviesController.cs
using Microsoft.AspNetCore.Authorization;
using System.Linq;

namespace Cinema_Hope.Controllers
{
    //[Authorize(Roles = "Admin")]
    public class MoviesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IGenresService _genresServices;   // Services
        private readonly IMovieService _movieService;   // Services
        private readonly IScreenService _screenService;   // Services
        private readonly ICinemaService _cinemaService;   // Services

        public MoviesController(ApplicationDbContext context, IGenresService genresServices, IMovieService movieService, IScreenService screenService, ICinemaService cinemaService)
        {
            _context = context;
            _genresServices = genresServices;
            _movieService = movieService;
            this._screenService = screenService;
            _cinemaService = cinemaService;
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            IEnumerable<Movie> movies = _movieService.GetAll();
            return View(movies);
        }

        public IActionResult Details(int id)
        {
            var movie = _movieService.GetById(id);

            if (movie is null)
                return NotFound();

            return View(movie);
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Create()
        {
            Create_MovieForm_ViewModel model = new()
            {
                AllGeners = _genresServices.GetSelectListOf_Genres()
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Create_MovieForm_ViewModel model)
        {
            if (!ModelState.IsValid)
            {
                // after that model is not vaild remember to initialize nessury field of model before return it.
                model.AllGeners = _genresServices.GetSelectListOf_Genres();
                    
                return View(model);
            }

            // Save Movie To Database
            // Save Movie Poster To Server.
            await _movieService.Create(model);

            return RedirectToAction(nameof(Index));
        }



        [HttpGet]
        public IActionResult Edit(int id)
        {
            Movie? movieInDB = _movieService.GetById(id);

            if (movieInDB is null)
                return NotFound();

            // pass data to ViewModel
            Edit_MovieForm_ViewModel viewModel = new()      // will use auto mapper instead of all these lines
            {
                MovieId = id,
                Title = movieInDB.Title,
                Description = movieInDB.Description,
                Director = movieInDB.Director,
                Duration = movieInDB.Duration,
                GenreId = movieInDB.GenreId,
                Language = movieInDB.Language,
                ProductionCompany = movieInDB.ProductionCompany,
                ReleaseDate = movieInDB.ReleaseDate,
                Writers = movieInDB.Writers,
                TrailerUrl = movieInDB.TrailerUrl,
                AllGeners = _genresServices.GetSelectListOf_Genres(),
                CurrentPoster = movieInDB.PosterUrl
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Edit_MovieForm_ViewModel model)
        {
            if (!ModelState.IsValid)
            {
                // after that model is not vaild remember to initialize nessury field of model before return it.
                model.AllGeners = _genresServices.GetSelectListOf_Genres();
                model.CurrentPoster = _movieService.GetById(model.MovieId).PosterUrl ?? "No Movie with Id ";


                return View(model);
            }

            // Save Movie To Database
            // Save Movie Poster To Server.
            var movie = await _movieService.Edit(model);

            if (movie is null)
                return BadRequest();

            return RedirectToAction(nameof(Index));
        }


        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var isDeleted = _movieService.Delete(id);

            return isDeleted ? Ok() : BadRequest();
        }


        public IActionResult AllMovies(string sort, string display)
        {
            // Get all the movies from the database
            var movies = _movieService.GetAll();

            // Apply sorting
            switch (sort)
            {
                case "new":
                    movies = movies.OrderByDescending(m => m.ReleaseDate);
                    break;

                case "old":
                    movies = movies.OrderBy(m => m.ReleaseDate);
                    break;

            }

            // Apply display order
            if (display == "desc")
            {
                movies = movies.Reverse();
            }

            // Create the view model with the filtered and sorted movies
            MoviesPage_ViewModel viewModel = new MoviesPage_ViewModel()
            {
                Movies = movies.ToList(),
                Screens = _screenService.GetSelectListOf_Screens(),
                Cinemas = _cinemaService.GetSelectListOf_Cinemas(),
                Genres = _genresServices.GetSelectListOf_Genres()
            };

            return View(viewModel);
        }


        public IActionResult Filter(string cinema, List<string> genres)
        {
            // Get all the movies from the database
            var movies = _movieService.GetAll();

            // Filter movies by cinema
            //if (!string.IsNullOrEmpty(cinema))
            //{
            //    movies = movies.Where(m => m.Showtimes.Cinema == cinema);
            //}

            // Filter movies by genres
            if (genres != null && genres.Count > 0)
            {
                movies = movies.Where(m =>  genres.Contains(m.Genre.GenreId.ToString()));
            }

            // Create the view model with the filtered movies
            MoviesPage_ViewModel viewModel = new MoviesPage_ViewModel()
            {
                Movies = movies.ToList(),
                Screens = _screenService.GetSelectListOf_Screens(),
                Cinemas = _cinemaService.GetSelectListOf_Cinemas(),
                Genres = _genresServices.GetSelectListOf_Genres()
            };

            return View("AllMovies", viewModel);
        }
    }
}

Cinema_Hope_Solution/Cinema_Hope/Controllers/SeatsController.cs
using Cinema_Hope.Models;
using Microsoft.AspNetCore.Authorization;

namespace Cinema_Hope.Controllers
{
    [Authorize(Roles = "Admin")]

    public class SeatsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ISeatService _seatService;
        private readonly IScreenService _screenService;
        private readonly IMapper _mapper;


        public SeatsController(ApplicationDbContext context, ISeatService seatService, IScreenService screenService, IMapper mapper)
        {
            _context = context;
            _seatService = seatService;
            _screenService = screenService;
            _mapper = mapper;
        }

        // GET: Seats
        public async Task<IActionResult> Index()
        {
            IEnumerable<Seat> seats = await _seatService.GetAllSeatsAsync();

            return View(seats);
        }



        // GET: Seats/Details/5
        public async Task<IActionResult> Details(int id)
        {
            Seat? seat = await _seatService.GetByIdAsync(id);

            if (seat is null)
                return NotFound();

            return View(seat);
        }


        [HttpGet]
        public IActionResult Create()
        {
            SeatFrom_ViewModel viewModel = new()
            {
                SelectListOfScreens = _screenService.GetSelectListOf_Screens()
            };

            return View(viewModel);
        }


        // POST: Seats/Create.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SeatFrom_ViewModel model)
        {
            if (!ModelState.IsValid)
            {
                // after that model is not vaild remember to initialize nessury field of model before return it.

                model.SelectListOfScreens = _screenService.GetSelectListOf_Screens();

                return View(model);
            }

            // let seat service do create and save to database

            await _seatService.Create(model);

            return RedirectToAction(nameof(Index));
        }


        // GET: Seats/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            Seat? seatInDB = await _seatService.GetByIdAsync(id);

            if (seatInDB is null)
                return NotFound();

            // pass data to ViewModel From Entity In DB
            SeatFrom_ViewModel viewModel = _mapper.Map<SeatFrom_ViewModel>(seatInDB);

            // do not forgot to map other nessary properties to View , like SelectListDropDwon
            viewModel.SelectListOfScreens = _screenService.GetSelectListOf_Screens();

            return View(viewModel);
        }


        // POST: Seats/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(SeatFrom_ViewModel model)
        {
            if (!ModelState.IsValid)
            {
                // after that model is not vaild remember to initialize nessury field of model before return it.

                model.SelectListOfScreens = _screenService.GetSelectListOf_Screens();

                return View(model);
            }

            // Edit Entity in Database using Service : var entity = _service.Edit(model)
            Seat? seatToDB = await _seatService.Edit(model);

            // check if entity null , means that BadRequest
            if (seatToDB is null)
                return BadRequest();

            return RedirectToAction(nameof(Index));
        }



        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            bool isDeleted = await _seatService.DeleteAsync(id);

            return isDeleted ? Ok() : BadRequest("Bad Request");

        }
    }
}

Cinema_Hope_Solution/Cinema_Hope/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Cinema_Hope.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public UsersController(UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }


        // Get List Of Users  With Their Role of each user
        public async Task<IActionResult> Index()
        {
            var users = await _userManager.Users.ToListAsync();
            var userViewModels = new List<UserViewModel>();
            foreach (var user in users)
            {
                var userRoles = await _userManager.GetRolesAsync(user);
                userViewModels.Add(new UserViewModel
                {
                    Id = user.Id,
                    UserName = user.UserName,
                    Email = user.Email,
                    PhoneNumber = user.PhoneNumber,
                    Roles = userRoles
                });
            }

            return View(userViewModels);
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(string id)
        {
            var userInDB = await _userManager.FindByIdAsync(id);
            if (userInDB == null)
                return NotFound();
            var result = await _userManager.DeleteAsync(userInDB);
            if (!result.Succeeded)
                throw new Exception();
            // Good
            return Ok();
        }


    }
}

Cinema_Hope_Solution/Cinema_Hope/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Cinema_Hope | @ViewData["Title"] </title>

    <!-- <link rel="stylesheet" href="~/AdminStyle/lib/bootstrap/dist/css/bootstrap.min.css" />  replaced with this under -->

    <link rel="stylesheet" href="~/AdminStyle/css/bootstrap.min.css" />

    <!--Bootstrap Icons -->
    <link rel="stylesheet" href="~/AdminStyle/lib/bootstrap-icons/font/bootstrap-icons.min.css" />


    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Chakra+Petch:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
        rel="stylesheet">

    <!-- File Of Styling Selectlist -->
    <link rel="stylesheet" href="~/AdminStyle/lib/select2/css/select2.min.css" />

    <!-- Sweet Alert -->
    <link rel="stylesheet" href="~/AdminStyle/lib/sweetalert2/sweetalert2.min.css" />

    <!-- This File Site.css Always Should be tha last bottom -->
    <link rel="stylesheet" href="~/AdminStyle/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AdminStyle/Cinema_Hope.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-light mb-3" data-bs-theme="light">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Cinema_Hope</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark"  asp-controller="Movies" asp-action="Index">Movies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Cinemas" asp-action="Index">Cinemas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Locations" asp-action="Index">Locations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Screens" asp-action="Index">Screens</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="ShowTimes" asp-action="Index">ShowTimes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Seats" asp-action="Index">Seats</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Customers" asp-action="Index">Customers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Bookings" asp-action="Index">Bookings</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Users" asp-action="Index">Users</a>
                        </li>
                       @*  <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Create New User</a>
                        </li> *@
                    </ul>
                    <partial name="_LoginPartial" />

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Cinema_Hope - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/AdminStyle/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/AdminStyle/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <!-- File Of Styling Selectlist -->
    <script src="~/AdminStyle/lib/select2/js/select2.min.js"></script>

    <!-- Sweet Alert -->
    <script src="~/AdminStyle/lib/sweetalert2/sweetalert2.min.js" asp-append-version="true"></script>

    <script src="~/AdminStyle/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>